"""init

Revision ID: 220e73af46b9
Revises: 
Create Date: 2021-10-10 17:18:57.283678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220e73af46b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=100), nullable=True),
    sa.Column('current_login_ip', sa.String(length=100), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cameratype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lens_k1', sa.Float(), nullable=False),
    sa.Column('lens_c', sa.Float(), nullable=False),
    sa.Column('lens_f', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('position_crs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bathymetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('crs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_type_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CAMERA_STATUS_INACTIVE', 'CAMERA_STATUS_ACTIVE', name='camerastatus'), nullable=False),
    sa.ForeignKeyConstraint(['camera_type_id'], ['cameratype.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratingcurve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('a', sa.Float(), nullable=True),
    sa.Column('b', sa.Float(), nullable=True),
    sa.Column('h0', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bathymetrycoordinate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bathymetry_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bathymetry_id'], ['bathymetry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('crs', sa.Integer(), nullable=True),
    sa.Column('movie_setting_resolution', sa.String(), nullable=True),
    sa.Column('movie_setting_fps', sa.Float(), nullable=True),
    sa.Column('gcps_src_0_x', sa.Integer(), nullable=True),
    sa.Column('gcps_src_0_y', sa.Integer(), nullable=True),
    sa.Column('gcps_src_1_x', sa.Integer(), nullable=True),
    sa.Column('gcps_src_1_y', sa.Integer(), nullable=True),
    sa.Column('gcps_src_2_x', sa.Integer(), nullable=True),
    sa.Column('gcps_src_2_y', sa.Integer(), nullable=True),
    sa.Column('gcps_src_3_x', sa.Integer(), nullable=True),
    sa.Column('gcps_src_3_y', sa.Integer(), nullable=True),
    sa.Column('gcps_dst_0_x', sa.Float(), nullable=True),
    sa.Column('gcps_dst_0_y', sa.Float(), nullable=True),
    sa.Column('gcps_dst_1_x', sa.Float(), nullable=True),
    sa.Column('gcps_dst_1_y', sa.Float(), nullable=True),
    sa.Column('gcps_dst_2_x', sa.Float(), nullable=True),
    sa.Column('gcps_dst_2_y', sa.Float(), nullable=True),
    sa.Column('gcps_dst_3_x', sa.Float(), nullable=True),
    sa.Column('gcps_dst_3_y', sa.Float(), nullable=True),
    sa.Column('gcps_z_0', sa.Float(), nullable=True),
    sa.Column('gcps_h_ref', sa.Float(), nullable=True),
    sa.Column('corner_up_left_x', sa.Integer(), nullable=True),
    sa.Column('corner_up_left_y', sa.Integer(), nullable=True),
    sa.Column('corner_up_right_x', sa.Integer(), nullable=True),
    sa.Column('corner_up_right_y', sa.Integer(), nullable=True),
    sa.Column('corner_down_left_x', sa.Integer(), nullable=True),
    sa.Column('corner_down_left_y', sa.Integer(), nullable=True),
    sa.Column('corner_down_right_x', sa.Integer(), nullable=True),
    sa.Column('corner_down_right_y', sa.Integer(), nullable=True),
    sa.Column('lens_position_x', sa.Float(), nullable=True),
    sa.Column('lens_position_y', sa.Float(), nullable=True),
    sa.Column('lens_position_z', sa.Float(), nullable=True),
    sa.Column('projection_pixel_size', sa.Float(), nullable=True),
    sa.Column('aoi_bbox', sa.Text(), nullable=True),
    sa.Column('aoi_window_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('file_bucket', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('MOVIE_TYPE_NORMAL', 'MOVIE_TYPE_CONFIG', name='movietype'), nullable=True),
    sa.Column('actual_water_level', sa.Float(), nullable=True),
    sa.Column('bathymetry_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('MOVIE_STATUS_NEW', 'MOVIE_STATUS_EXTRACTED', 'MOVIE_STATUS_PROCESSING', 'MOVIE_STATUS_FINISHED', 'MOVIE_STATUS_ERROR', name='moviestatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('discharge_q05', sa.Float(), nullable=True),
    sa.Column('discharge_q25', sa.Float(), nullable=True),
    sa.Column('discharge_q50', sa.Float(), nullable=True),
    sa.Column('discharge_q75', sa.Float(), nullable=True),
    sa.Column('discharge_q95', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bathymetry_id'], ['bathymetry.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratingpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ratingcurve_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('include', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['ratingcurve_id'], ['ratingcurve.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratingpoint')
    op.drop_table('movie')
    op.drop_table('configuration')
    op.drop_table('bathymetrycoordinate')
    op.drop_table('ratingcurve')
    op.drop_table('camera')
    op.drop_table('bathymetry')
    op.drop_table('site')
    op.drop_table('roles_users')
    op.drop_table('cameratype')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
