"""Remove error message field from Movie

Revision ID: bd112e5dfe7d
Revises: 2dc4e9f8d49a
Create Date: 2021-07-27 23:48:47.739385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd112e5dfe7d'
down_revision = '2dc4e9f8d49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'error_message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
