"""Add error field to Movie model

Revision ID: cac0b6767b4c
Revises: bd112e5dfe7d
Create Date: 2021-07-28 09:18:59.295868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac0b6767b4c'
down_revision = 'bd112e5dfe7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'error_message')
    # ### end Alembic commands ###
